package com.demo.ws.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-05-23T09:14:55.535-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.cleverbuilder.com/BookService/", name = "BookService")
@XmlSeeAlso({ObjectFactory.class})
public interface BookService {

    @WebMethod(operationName = "GetBook", action = "http://www.cleverbuilder.com/BookService/GetBook")
    @RequestWrapper(localName = "GetBook", targetNamespace = "http://www.cleverbuilder.com/BookService/", className = "com.demo.ws.GetBook")
    @ResponseWrapper(localName = "GetBookResponse", targetNamespace = "http://www.cleverbuilder.com/BookService/", className = "com.demo.ws.GetBookResponse")
    public void getBook(
            @WebParam(mode = WebParam.Mode.INOUT, name = "ID", targetNamespace = "")
                    javax.xml.ws.Holder<String> id,
            @WebParam(mode = WebParam.Mode.OUT, name = "Title", targetNamespace = "")
                    javax.xml.ws.Holder<String> title,
            @WebParam(mode = WebParam.Mode.OUT, name = "Author", targetNamespace = "")
                    javax.xml.ws.Holder<String> author
    );

    @WebMethod(operationName = "AddBook", action = "http://www.cleverbuilder.com/BookService/AddBook")
    @RequestWrapper(localName = "AddBook", targetNamespace = "http://www.cleverbuilder.com/BookService/", className = "com.demo.ws.AddBook")
    @ResponseWrapper(localName = "AddBookResponse", targetNamespace = "http://www.cleverbuilder.com/BookService/", className = "com.demo.ws.AddBookResponse")
    @WebResult(name = "ID", targetNamespace = "")
    public String addBook(
            @WebParam(name = "Title", targetNamespace = "")
                    String title,
            @WebParam(name = "Author", targetNamespace = "")
                    String author
    );

    @WebMethod(operationName = "GetAllBooks", action = "http://www.cleverbuilder.com/BookService/GetAllBooks")
    @RequestWrapper(localName = "GetAllBooks", targetNamespace = "http://www.cleverbuilder.com/BookService/", className = "com.demo.ws.GetAllBooks")
    @ResponseWrapper(localName = "GetAllBooksResponse", targetNamespace = "http://www.cleverbuilder.com/BookService/", className = "com.demo.ws.GetAllBooksResponse")
    @WebResult(name = "Book", targetNamespace = "")
    public java.util.List<GetAllBooksResponse.Book> getAllBooks();
}
